[package]
name = "wifi-connect"
version = "4.2.10"
authors = ["Zahari Petkov <zahari@balena.io>"]
description = "Easy WiFi setup for Linux devices from your mobile phone or laptop"
homepage = "https://github.com/resin-io/resin-wifi-connect"
license = "Apache-2.0"

[dependencies]
network-manager = "0.11"
clap = "2.24"
iron = "0.6"
iron-cors = "0.7"
staticfile = "0.5"
mount = "0.4"
router = "0.6"
serde = "1.0"
serde_json = "1.0"
serde_derive = "1.0"
persistent = "0.4"
params = "0.8"
log = "0.3"
env_logger = "0.4"
nix = "0.10"

[dependencies.error-chain]
version = "0.11"
default-features = false

[profile.release]
panic = "abort"
lto = true
codegen-units = 1
incremental = false
opt-level = "z"
